### ISSUE TITLE
Vertical marker dashed line rendering issue

### ISSUE THREAD

**Issue by metro69** [wavedrom/wavedrom#119]
Wavedrom uses paths to implement the vertical dashed cycle markers.

It looks like some tools do not render such paths correctly. I have attached pdf output from Inkscape. I see the same problem in fop based flow.

Is it possible to change this to line instead?

MT

![image](https://cloud.githubusercontent.com/assets/11471154/9860613/1d1fa8b0-5ae2-11e5-9d59-e4e2681a2e23.png)

**Comment by drom** [comment]
just fixed https://github.com/wavedrom/wavedrom/commit/938290355db813598f6654ee1939bb9e37c560dd
