### ISSUE TITLE
hscale or period with values smaller 1

### ISSUE THREAD

**Issue by frankbenoit** [wavedrom/wavedrom#123]
Hi,

if the diagram is having lots of clocks, I want to shrink it appropriately. But only value >= 1 are accepted. Can this made possible?

Frank

**Comment by drom** [comment]
It was discussed in #108 #70

**Comment by slacAWallace** [comment]
Is period allowed to be less than 1? Seems to be partially working, but it messes up node alignment.

**Comment by drom** [comment]
In general, the tool only supports a period of 1, 1.5, 2, 2.5,...
In some cases, period = 0.5 also partially work.
