### ISSUE TITLE
Add register description image generation function

### ISSUE THREAD

**Issue by kenaken** [wavedrom/wavedrom#157]
It may be very usefull to have a tool, that will generate register description picture like in [NXP documentation](http://cache.nxp.com/files/32bit/doc/ref_manual/MPC5553_MPC5554_RM.pdf?fpsp=1&WT_TYPE=Reference%20Manuals&WT_VENDOR=FREESCALE&WT_FILE_FORMAT=pdf&WT_ASSET=Documentation&fileExt=.pdf) (page 199).

![Register description image](http://funkyimg.com/i/2c1RS.png)

It seems to be very similar with geneating timing diagrams and will be nice addition to WaveDrom.

**Comment by drom** [comment]
@Thoragan the first shocking thing on this picture (to my LE brain) is BE order of bits ;)

**Comment by drom** [comment]
@Thoragan in fact I have standalone package with this functionality: https://github.com/drom/bitfield
I will work to make it more accessible. Please file all feature requests there.
It is extraction from old version of WaveDrom and at some point I am going to integrate it back.

**Comment by drom** [comment]
LGTM
