### ISSUE TITLE
WaveDrom preview package for Atom editor

### ISSUE THREAD

**Issue by cdwilson** [wavedrom/wavedrom#179]
Would it be possible to add a WaveDrom preview package for Atom editor (https://atom.io)?

Something like https://github.com/atom/markdown-preview

**Comment by drom** [comment]
@cdwilson I am 100% for it. I am using Atom daily. Do you use it?

And I have seeing many cases of WaveDrom inside MarkDown like this https://github.com/drjson/stackedit-wavedrom
or AsciiDoctor : https://github.com/asciidoctor/asciidoctor-diagram

Don't have time to do it now, so any help are welcome.

**Comment by alexisfrjp** [comment]
That exists: https://atom.io/packages/markdown-preview-enhanced
Please close the issue.
