### ISSUE TITLE
64-bit register support

### ISSUE THREAD

**Issue by kiwidoggie** [wavedrom/wavedrom#216]
Please describe your system environment before submitting your Issue.

Hello, I am using the web editor, and noticed that the register bit count only goes up to 32. Is there any way to get a 64 bit variant? (reg64?)

**Comment by drom** [comment]
You can configure the register diagram this way:
```js
{reg: [
  {bits: 7, name: 'F1'},
  {bits: 50},
  {bits: 7, name: 'F2'},
], config:{bits: 64}}
```

Awailable optionas are here: https://github.com/drom/bitfield

**Comment by kiwidoggie** [comment]
Thank you
