### ISSUE TITLE
reg before signal in one file causes bad signal rendering

### ISSUE THREAD

**Issue by joshuascheid** [wavedrom/wavedrom#221]
Observed with:
Linux Chromium 71.0.3578.98 
Linux Firefox 60.6.0esr

Apply patch below (reorder first signal after first reg).

Expected: signal renders normally.
Actual: 
![Screenshot at 2019-04-03 17-24-24](https://user-images.githubusercontent.com/31359067/55521388-6b99ae80-5635-11e9-958f-e134d680db32.png)

Patch to appy to demonstrate issue:
https://gist.github.com/joshuascheid/eddba048bf17d869f9eca3b5c7f851af

**Comment by drom** [comment]
should be fixed
