### ISSUE TITLE
Option to hide vertical markers

### ISSUE THREAD

**Issue by jtechau** [wavedrom/wavedrom#227]
It would be nice to add a feature to optionally remove the vertical cycle markers.  This would allow the user to create timing diagrams that have an asynchronous appearance (even though waveforms are still aligned to an invisible grid).

Perhaps this could even be the default if no clock waveform is defined?

Reference:  https://groups.google.com/d/msg/wavedrom/YeYtBjqogUM/t6eWpFg7BwAJ

**Comment by drom** [comment]
When `config:{marks:false}` wavedrom will not render vertical dotted lines. Is that sufficient?

**Comment by jtechau** [comment]
That sounds perfect.

**Comment by drom** [comment]
in wavedrom v2.1.0 and online at https://wavedrom.com now
