### ISSUE TITLE
Gated clock implementation - glitch on ungate

### ISSUE THREAD

**Issue by ghanashyamprabhu** [wavedrom/wavedrom#234]
Am using the below code to implement a gated clock waveform - the ungated clock, the gated clock and the clock enable are shown. Why do I see a glitch at the clock cycle where clock is gated again second time?

```
{ "signal" : [
   { "name": "clk",        "wave": "p.......|........" },
  { "name": "clk_enable",  "wave": "0..1....|...0...." },
  
   { "name": "gated_clk",  "wave": "0...p...|....0..." }
]}
```
Can you please help resolving this issue? 

![image](https://user-images.githubusercontent.com/385510/58694239-2df4a000-83b0-11e9-96a8-0e279c8ef89e.png)

Regards
ghanashyam

**Comment by drom** [comment]
Just use `l` instead of `0`

**Comment by ghanashyamprabhu** [comment]
Below is the updated code with `1` instead of `0` - The clock pulls high which is not what I intend on clock gate. On clock gate, the clock needs to park low. 
```
{ "signal" : [
   { "name": "clk",        "wave": "p.......|........" },
  { "name": "clk_enable",  "wave": "0..1....|...0...." },
 
   { "name": "gated_clk",  "wave": "0...p...|....1..." } // changed 0 to 1 
]}

```
![image](https://user-images.githubusercontent.com/385510/58747969-e2b1be80-848f-11e9-90cf-c0e5ba71bfb0.png)

**Comment by drom** [comment]
Not `1` as ONE but `l` as (Low case LETTER L)

**Comment by ghanashyamprabhu** [comment]
Thanks that resolves, Pasting the code here for completion
```
{ "signal" : [
   { "name": "clk",        "wave": "p.......|........" },
  { "name": "clk_enable",  "wave": "0..1....|...0...." },
 
   { "name": "gated_clk",  "wave": "0...p...|....l..." }
]}
```
![image](https://user-images.githubusercontent.com/385510/58757200-d8da9a80-8525-11e9-859e-97134ec9f584.png)
