### ISSUE TITLE
How to left align a heading?

### ISSUE THREAD

**Issue by codspalaniappan95** [wavedrom/wavedrom#237]
I am using wavedrom on jupyter notebook. I am trying to display the heading of the plot as a left align , but it automatically gets center aligned. Any idea how to do this?

**Comment by drom** [comment]
Any `text` item inside WaveJson is a `JSONML` element. So, you can do any SVG tricks:

```js
{signal: [
  {name:'clk',         wave: 'p....' },
  {name:'Data',        wave: 'x345x', data: 'a b c' },
  {name:'Request',     wave: '01..0' }
],
 head:{
   text: ['tspan', {'text-anchor': 'end', x: 200}, 'WaveDrom example'],
   tick:0,
 },
 foot:{
   text: ['tspan', {'text-anchor': 'start', x: 0}, 'Figure 100'],
   tock:9
 },
}
```

![](https://svg.wavedrom.com/{signal:[{name:'clk',wave:'p....'},{name:'Data',wave:'x345x',data:['a','b','c']},{name:'Request',wave:'01..0'}],head:{text:['tspan',{'text-anchor':'end',x:200},'WaveDrom_example'],tick:0},foot:{text:['tspan',{'text-anchor':'start',x:0},'Figure%20100'],tock:9}})
