### ISSUE TITLE
how to show 64 bit registers or longer using reg class?

### ISSUE THREAD

**Issue by rajah-ketos** [wavedrom/wavedrom#239]
Please describe your system environment before submitting your Issue.

**Comment by drom** [comment]
`bitfiled` options https://github.com/drom/bitfield are available via config property:

```js
{reg:[
  {bits:8,name:'foo'},
  {bits:48},
  {bits:8,name:'bar'}
],config:{bits:64,lanes:2}}
```
Here is more examples:
https://observablehq.com/@drom/quark?collection=@drom/wavedrom
