### ISSUE TITLE
How to do that？

### ISSUE THREAD

**Issue by PYGC** [wavedrom/wavedrom#240]
Please describe your system environment before submitting your Issue.

![微信图片_20190703102618](https://user-images.githubusercontent.com/16513529/60558829-2e040900-9d7d-11e9-9bbf-9ed66ffeb3e0.png)

**Comment by drom** [comment]
```js
{signal: [
  {name: 'CLK', wave: 'p..|.|....'},
  {name: 'RXD', wave: 'x=.|=<=|>===x', data: ['PREAMBLE', 'SFD', '', '', '', 'FCS']},
  {name: '???', wave: '0..|.|....'}
]}
```
Here is the trick:

![wavedrom](https://user-images.githubusercontent.com/511872/60780175-3304e780-a0f2-11e9-9f6b-a319d7c400fb.png)

**Comment by drom** [comment]
I was thinking of adding `#` symbol to this, particularly popular case. :thinking: 

Related to #213
