### ISSUE TITLE
Clock frequency change 

### ISSUE THREAD

**Issue by ghanashyamprabhu** [wavedrom/wavedrom#242]
Is there a way I can represent a clock frequency switch in a clock signal without glitchy behavior 

`{ "name": "clk",  "wave": "P.........npnpnpnpnpnpnpnp"}, `
The above code has a clock that changes its frequency from F to F/2 and the change happens at the negedge of the clock signal. This code has some glitchy signal rather than a clean clock as shown in the snapshot below

![image](https://user-images.githubusercontent.com/385510/61118437-5c3cc380-a4b6-11e9-9d1c-1692b09c1ce0.png)

-ghanashyam

**Comment by drom** [comment]
Use `l`, `L`, 'h`, `H` chars:

```js
{signal:[{name:'clk',wave:'P.....lHlHlHlH'}]}
```
<img src="https://svg.wavedrom.com/{signal:[{name:'clk',wave:'P.....HlHlHlH'}]}"/>

**Comment by ghanashyamprabhu** [comment]
Note the change of period at the negedge of the clk. With the  code that
you have suggested, at the point of frequency change, the negative phase of
the clock has the (old period)/2 as well as (new clock period)/2

**Comment by drom** [comment]
```
{signal:[{name:'clk',wave:'P.....lHlHlHlH'}]}
```
<img src="https://svg.wavedrom.com/{signal:[{name:'clk',wave:'P.....lHlHlHlH'}]}"/>

Closer?

**Comment by ghanashyamprabhu** [comment]
```
{signal:[{name:'clk',wave:'P.....<l>HlHlHlH'}]}
```

does the trick! Thanks much, this is useful. I couldn't find this on the tutorial page though..

**Comment by drom** [comment]
Yes, I have created a separate issue to document sub-cycle feature here: https://github.com/wavedrom/wavedrom/issues/243

**Comment by ghanashyamprabhu** [comment]
While we are at it, can I also make a separate signal which is a pulse occurring from the posedge to posedge at the clock cycle where the frequency changed in the w/f that I posted in question?

**Comment by drom** [comment]
Something like this?

<img src="https://svg.wavedrom.com/{signal:[{name:'clk',wave:'P...<l>HlHlH'},{name:'change',wave:'0..h<.>l....'}]}"/>

In theory, it should look like this:

```js
{signal:[
  {name:'clk',    wave:'P...<l>HlHlH'},
  {name:'change', wave:'0..h<.>l....'}
]}
``` 

But in practice, it is broken.

**Comment by lilyoba** [comment]
> ```
> {signal:[{name:'clk',wave:'P.....lHlHlHlH'}]}
> ```
> 
> ![](https://camo.githubusercontent.com/05023e031d88626cda60d8f0f79e666bcbe2ec86ebbee886c09bfc2cbe63f2e3/68747470733a2f2f7376672e7761766564726f6d2e636f6d2f7b7369676e616c3a5b7b6e616d653a27636c6b272c776176653a27502e2e2e2e2e6c486c486c486c48277d5d7d)
> 
> or
> 
> ```
> {signal:[{name:'clk',wave:'P.....<l>HlHlHlH'}]}
> ```
> 
> ![](https://camo.githubusercontent.com/cc08a557172fb240fb1ae7d3301c5a0d1e14da4eb76459c2fd79996f7860a86d/68747470733a2f2f7376672e7761766564726f6d2e636f6d2f7b7369676e616c3a5b7b6e616d653a27636c6b272c776176653a27502e2e2e2e2e3c6c3e486c486c486c48277d5d7d)
> 
> Closer?

I am wondering how to generate this kind of waveform, thank you very much
