### ISSUE TITLE
Prince warning caused by WaveDrom generated SVG

### ISSUE THREAD

**Issue by jmilstead-sifive** [wavedrom/wavedrom#246]
An SVG generated by WaveDrom produces the following warning in Prince:
 
`warning: unsupported properties: enable-background
`

The workaround was to open the SVG in a text editor and delete all 5 instances of  `enable-background:accumulate`

**Comment by nschwass** [comment]
I'm going to resuscitate this issues page with some images to corroborate Jeff's gripes here. The figure below shows what happens in .pdf output when you remove those background-accumulate. Although this seems to be a prince problem vs. a wavedrom problem, it would be nice to have a workaround for the time being.
![image](https://user-images.githubusercontent.com/56890987/82500074-9fd56600-9aa7-11ea-86fc-468c40b4a768.png)

**Comment by drom** [comment]
I will fix it.
