### ISSUE TITLE
Mixed page with Register and Waveforms... Waveforms must go first.

### ISSUE THREAD

**Issue by davidthings** [wavedrom/wavedrom#258]
Linux (Ubuntu) / Chrome / Jekyll / 

I'm making a long (too long..) doc page with mixed graphics.

When I put a WaveDrom register diagram first, subsequent WaveDrom wave diagrams don't render properly.  No errors in the Inspector.

An empty Wave will fix it.  When I put the following at the top of the file, all is well.  Registers render fine, later Waves also render fine.

<script type="WaveDrom"> { signal: [ ] } </script>

Here's what it should look like

![image](https://user-images.githubusercontent.com/601105/65660751-82b5c980-dfe4-11e9-9126-c2490c033ae4.png)

When the above first Wave line is removed, bad things happen.

![image](https://user-images.githubusercontent.com/601105/65660827-c4467480-dfe4-11e9-8413-a84a31cd4778.png)

Let me know if I can do any further testing!

**Comment by drom** [comment]
That is because only the first diagram on the page carry wave brick drawings. I will fix.
