### ISSUE TITLE
Bus Transitions to High-Impedance State Not Rendered Correctly

### ISSUE THREAD

**Issue by Ganesh-AT** [wavedrom/wavedrom#264]
WaveDrom Online Editor on Firefox 70.0.b3 / Windows 10 x64
WaveDrom Online Editor on Firefox 60.8.0esr / RHEL 6 

While attempting to create a signal with transitions from valid bus state to high-impedance, and it appears that the transition is not rendered correctly

https://tinyurl.com/y2lfksxf

![wavedrom](https://user-images.githubusercontent.com/6980722/67117897-92b26a80-f198-11e9-8f40-d281d321776f.png)

Expected behavior - The change from multi-bit bus value to z must involve sharp lines (similar to the z to multi-bit bus value change) and not curved ones

Observed behavior - We get curved lines while transitioning from multi-bit to z, as shown in the picture above.

**Comment by drom** [comment]
It is intended and correct behavior. The drawing represents the fact that transition into High Impedance state takes time.

**Comment by Ganesh-AT** [comment]
Thank you for the clarification.

**Comment by derchr** [comment]
Is there a way to disable this?

**Comment by drom** [comment]
@derchr what is your use case?

**Comment by derchr** [comment]
> [@derchr](https://github.com/derchr) what is your use case?

My plan was to visualize SystemC TLM-AT protocol phases alongside RTL signals, but the slope makes it look weird:

<img width="640" height="180" alt="Image" src="https://github.com/user-attachments/assets/54e1d314-1808-4c46-b214-295bcec43a7c" />
