### ISSUE TITLE
Is there a reserved API interface for generating SVG files

### ISSUE THREAD

**Issue by pppigg** [wavedrom/wavedrom#275]
I now have a json data file with a size of 1kb. When I open the file with `wavedrom-editor.exe`, the sequence diagram loaded by the software will not be smooth to look at. After exporting the SVG file, it is smooth to look at the sequence diagram.So I want to know if there is an API interface that allows me to export SVG files directly.
Looking forward to your reply. Thank you!

**Comment by drom** [comment]
Could you be more specific with your question?
