### ISSUE TITLE
Waveform can't be displayed on Chrome/IE now

### ISSUE THREAD

**Issue by Justinccy** [wavedrom/wavedrom#280]
And it looks like this
![image](https://user-images.githubusercontent.com/19799648/74133308-43021e00-4c23-11ea-8018-4dcb5bdf8bb6.png)

**Comment by PinHui** [comment]
I meet same problem.

**Comment by drom** [comment]
Should be fixed in v2.3.2
Please try.

**Comment by Justinccy** [comment]
It works. Many thanks.
