### ISSUE TITLE
Which font is used in wavedrom?

### ISSUE THREAD

**Issue by igorrz** [wavedrom/wavedrom#290]
Windows 10, Firefox.
The editor is veery helpful, but I have some issues with editing text on the arrows. For example I would like to be able to set a new line via \n or to move the text a little bit to avoid an overlapping. That is why I was thinking about using some extrnal image editing program just to insert few strings by myself. To do so I need to know the font used in the arrow-text. 
Thank you in adcance for your support!

**Comment by drom** [comment]
`font-family: Helvetica;`
