### ISSUE TITLE
time unit on ticks/tocks?

### ISSUE THREAD

**Issue by nachiket** [wavedrom/wavedrom#297]
Is it possible to add time units to the tick marks? i.e. for the tick example in the tutorial,

`
head:{   text:'WaveDrom example',   tick:0, },
`

I want to ticks to read as 0ns, 1ns, 2ns, etc...

**Comment by drom** [comment]
`tick` can be a <string> of space-separated labels. Like this:

```wavedrom
{signal: [
  {name:'clk',         wave: 'p....' },
  {name:'Data',        wave: 'x345x', data: 'a b c' },
  {name:'Request',     wave: '01..0' }
],
 head:{
   text:'WaveDrom example',
   tick: '0ns 1ns 2ns 3ns 4ns 5ns ',
 }
}
```

**Comment by nachiket** [comment]
That's it! Thanks.
