### ISSUE TITLE
Regression: tspan in signal name doesn't work anymore

### ISSUE THREAD

**Issue by frasten** [wavedrom/wavedrom#299]
I'm trying to change the label color for a waveform. It used to work in some previous version by putting a `tspan` with a custom style inside the `name` of the waveform.

Unfortunately this code isn't working anymore (I'm using the official wavedrom editor):
```javascript
{signal: [
    {name: ['tspan', {style: 'fill: red'}, 'Test'], wave: '0HL'}
]}
```
I get this error in the browser console::
> TypeError: str.charCodeAt is not a function

For comparison, the code without the styling is as simple as:
```javascript
{signal: [
    {name: 'Test', wave: '0HL'}
]}
```

Thank you for your awesome tool.

**Comment by drom** [comment]
You can use `tspan` styling in most of the text labels, except the `name`.
The `name` is special because I have to measure the width of this text to let enough space on the left.
You can use some https://github.com/drom/tspan markup inside the text.

**Comment by frasten** [comment]
Thank you for your reply. Is there any other way to change the label color? I could have misread the docs, but tspan maskup doesn't seem to be able to change it.

**Comment by jwhavican** [comment]
I agree that it would be really useful to be able to change the label color.

By the way, thanks for developing this tool, it is awesome!
